(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/gaoyia-parse/components/wxParseTemplate8"],{1890:function(e,n,t){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var a=function(){return t.e("components/gaoyia-parse/components/wxParseTemplate9").then(t.bind(null,"3473"))},r=function(){return t.e("components/gaoyia-parse/components/wxParseImg").then(t.bind(null,"99bc"))},o=function(){return t.e("components/gaoyia-parse/components/wxParseVideo").then(t.bind(null,"ee1d"))},c=function(){return t.e("components/gaoyia-parse/components/wxParseAudio").then(t.bind(null,"951b"))},u=function(){return t.e("components/gaoyia-parse/components/wxParseTable").then(t.bind(null,"b397"))},s={name:"wxParseTemplate8",props:{node:{}},components:{wxParseTemplate:a,wxParseImg:r,wxParseVideo:o,wxParseAudio:c,wxParseTable:u},methods:{wxParseATap:function(e,n){var t=n.currentTarget.dataset.href;if(t){var a=this.$parent;while(!a.preview||"function"!==typeof a.preview)a=a.$parent;a.navigate(t,n,e)}}}};n.default=s},"1c0d":function(e,n,t){"use strict";t.r(n);var a=t("1890"),r=t.n(a);for(var o in a)"default"!==o&&function(e){t.d(n,e,function(){return a[e]})}(o);n["default"]=r.a},c7b6:function(e,n,t){"use strict";t.r(n);var a=t("cce4"),r=t("1c0d");for(var o in r)"default"!==o&&function(e){t.d(n,e,function(){return r[e]})}(o);var c,u=t("f0c5"),s=Object(u["a"])(r["default"],a["b"],a["c"],!1,null,null,null,!1,a["a"],c);n["default"]=s.exports},cce4:function(e,n,t){"use strict";var a,r=function(){var e=this,n=e.$createElement;e._self._c},o=[];t.d(n,"b",function(){return r}),t.d(n,"c",function(){return o}),t.d(n,"a",function(){return a})}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/gaoyia-parse/components/wxParseTemplate8-create-component',
    {
        'components/gaoyia-parse/components/wxParseTemplate8-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("c7b6"))
        })
    },
    [['components/gaoyia-parse/components/wxParseTemplate8-create-component']]
]);
